{{ if .Values.envs }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "generic.fullname" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
data:
  {{- toYaml .Values.envs | nindent 2 }}
{{ end }}
