{{- $fullName := include "generic.fullname" . -}}
{{- $secretName := default $fullName .Values.externalSecrets.secret.name }}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.secret.APIversion }}
kind: ExternalSecret
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecrets.secret.refreshInterval }}
  secretStoreRef:
    name: {{ $fullName }}
    kind: SecretStore
  target:
    name: {{ $fullName }}
    creationPolicy: Owner
  {{- if .Values.externalSecrets.secret.fetchAllFrom }}
  dataFrom:
  - extract:
      key: {{ .Values.externalSecrets.secret.fetchAllFrom }}
  {{- else }}
  data:
  {{- toYaml .Values.externalSecrets.secret.data | nindent 2 }}
  {{- end  }}
{{- end }}
