{{- $fullName := include "generic.fullname" . -}}
{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/{{ .Values.externalSecrets.store.APIversion }}
kind: SecretStore
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
spec:
  provider:
    aws:
      region: "{{ .Values.externalSecrets.store.awsRegion }}"
      role: "{{ .Values.externalSecrets.store.fetchRoleARN }}"
      service: SecretsManager
{{- end }}