{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "generic.serviceAccountName" . }}
  labels:
    {{- include "generic.labels" . | nindent 4 }}
  {{- $annotations := dict }}
  {{- with .Values.serviceAccount.annotations }}
  {{- $annotations = merge $annotations . }}
  {{- end }}

  {{- if not (empty $annotations) }}
  annotations:
  {{- toYaml $annotations | nindent 4 }}
  {{- end }}
{{- end }}
